Usama/blog/blog item
merge-stack/mergestack.com pull request #17
Opened 2023-11-01 14:58 UTC by UzeeChamp1

WORK IN PROGRESS

Blogs has been designde, Blogs are yet to be added

2023-11-02 08:09 UTC, alitjanjua requested changes

2023-11-02 08:09 UTC, alitjanjua commented on src/components/blog/blogs/blog-item.tsx
> +import React from 'react';
@UzeeChamp1 component name should start with Capital letter and shouldn't contain alphanumeric letters
```suggestion
src/components/blog/BlogItem.tsx
```

2023-11-02 08:11 UTC, UzeeChamp1 commented on src/components/blog/blogs/blog-item.tsx
> +import React from 'react';
actually the component function name is already in camel case, this is just a file name, Should I change it too?

2023-11-13 11:51 UTC, alitjanjua approved these changes

2023-11-13 12:56 UTC, alitjanjua commented on pages/blogs.tsx
> +import { Box, Container } from '@mui/material';
@UzeeChamp1 when you have unused imports, pls remove them

2023-11-13 12:56 UTC, alitjanjua commented on src/components/blog/blogs/BlogItem.tsx
> +interface BlogItemProps {
@UzeeChamp1 pls start the interface name with capital i(I)
```suggestion
interface IBlogItemProps {
```

2023-11-13 12:56 UTC, alitjanjua commented on src/components/blog/blogs/index.tsx
> +  const handleLoadMore = () => {
@UzeeChamp1 when you start writing functions in component, make sure to add empty line before them
```suggestion

  const handleLoadMore = () => {
```

2023-11-13 13:01 UTC, merged